name: dConnect-sdk-for-android CI

on: [push, pull_request]

jobs:
  release:
    name: release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Build project
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          cmd: ./gradlew connectedCheck --stacktrace
          api: 29
          tag: default
          abi: x86_64
          cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -timezone Asia/Tokyo
      - name: Generate Javadoc For SDK
        if: always()
        run: ./gradlew generateJavadocForSDK
      - name: Generate Javadoc For SDKJUnit
        if: always()
        run: ./gradlew generateJavadocForSDKJUnit
      - name: Publish AAR
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease publish    
      - name: Upload apk file
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Upload dconnect-sdk-for-android release aar
          path: dconnect-sdk-for-android/build/outputs/aar/dconnect-sdk-for-android-release.aar
      - name: Pack test result and document in zip file
        if: always()
        run: |
          sudo zip -r DeviceConnectSDK-Javadoc.zip ./DeviceConnectSDK-Javadoc
          sudo zip -r DeviceConnectSDK-JUnit-Javadoc.zip ./DeviceConnectSDK-JUnit-Javadoc
          cd dconnect-sdk-for-android/build/reports/androidTests
          sudo mv connected code-coverage-report
          sudo zip -r release.zip ./code-coverage-report
      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: dconnect-sdk-for-android/build/reports/androidTests/release.zip
      - name: Archive DeviceConnectSDK-Javadoc
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: DeviceConnectSDK-Javadoc
          path: DeviceConnectSDK-Javadoc.zip
      - name: Archive DeviceConnectSDK-Javadoc
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: DeviceConnectSDK-JUnit-Javadoc
          path: DeviceConnectSDK-JUnit-Javadoc.zip
