name: CI

on: [push, pull_request]

jobs:
  build:
    name: dConnect-sdk-for-android
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Build project
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: |
          chmod +x ./gradlew
          sudo ./gradlew assembleRelease
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          cmd: sudo ./gradlew connectedCheck --stacktrace
          api: 29
          tag: default
          abi: x86_64
          cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -timezone Asia/Tokyo
      - name: Publish AAR
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: ./gradlew assembleRelease publish    
      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: Upload dconnect-sdk-for-android release aar
          path: dconnect-sdk-for-android/build/outputs/aar/dconnect-sdk-for-android-release.aar
      - name: Pack source code in zip file
        run: |
          cd dconnect-sdk-for-android/build/reports/androidTests
          sudo mv connected code-coverage-report
          sudo zip -r release.zip ./code-coverage-report
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: dconnect-sdk-for-android/build/reports/androidTests/release.zip
