name: CI

on: [push, pull_request]

jobs:
  build:
    name: dConnect-sdk-for-android
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [23]
        target: [google_apis]
    steps:
      - name: Set Time Zone
        run: TZ=Asia/Tokyo
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Build project
        run: |
          pwd
          echo "${{ secrets.GPR_USER }}"
          export GPR_USER="${{ secrets.GPR_USER }}"
          export GPR_API_KEY="${{ secrets.GPR_API_KEY }}"
          chmod +x ./gradlew
          sudo ./gradlew assemble --stacktrace
      - name: show Directory
        run: |
          pwd
          ls ../
          java -version
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: sudo ./gradlew connectedCheck
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: dconnect-sdk-for-android/build/reports/androidTests/connected/index.html
