name: CI

on: [push, pull_request]

jobs:
  build:
    name: dConnect-sdk-for-android
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Build project
        run: |
          pwd
          echo "${{ secrets.GPR_USER }}"
          export GPR_USER="${{ secrets.GPR_USER }}"
          export GPR_API_KEY="${{ secrets.GPR_API_KEY }}"
          chmod +x ./gradlew
          sudo ./gradlew assembleDebug --stacktrace
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          cmd: sudo ./gradlew connectedCheck --stacktrace
          api: 29
          tag: default
          abi: x86_64
          cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -timezone Asia/Tokyo
      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: aar
          path: dconnect-sdk-for-android/build/outputs/aar/dconnect-sdk-for-android-debug.aar
      - name: Pack source code in zip file
        run: |
          zip -r dconnect-sdk-for-android/build/reports/androidTests/release.zip dconnect-sdk-for-android/build/reports/androidTests/connected
          ls
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: release.zip
