name: CI

on: [push, pull_request]

jobs:
  build:
    name: dConnect-sdk-for-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Build project
        run: |
          pwd
          echo "${{ secrets.GPR_USER }}"
          export GPR_USER="${{ secrets.GPR_USER }}"
          export GPR_API_KEY="${{ secrets.GPR_API_KEY }}"
          chmod +x ./gradlew
          sudo ./gradlew assembleDebug --stacktrace
      - name: "Run UI Tests"
        uses: vgaidarji/android-github-actions-emulator@v1.0.1
      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: dconnect-sdk-for-android/build/reports/androidTests/connected/index.html
